### ISSUE TITLE
this.fb.browserInit(this.FB_APP_ID, "v2.8");

### ISSUE THREAD

**Issue by tomNjerry** [ionicthemes/ionic2-facebook-login#2]
This line of code of opening the browser is not initiating 
i ,m using the 
 "@ionic-native/core": "3.12.1",
   "cordova-android": "^6.2.3",
   "@ionic-native/facebook": "^4.1.0"

Please help with the code

**Comment by djabif** [comment]
Where are you testing the app?

**Comment by tomNjerry** [comment]
local machine
