### ISSUE TITLE
how can get the auth code in return instead of data

### ISSUE THREAD

**Issue by tomNjerry** [ionicthemes/ionic2-facebook-login#3]
i want to get the access code from facebook graph in return

**Comment by tiagomestreteixeira** [comment]
@tomNjerry From the sample code in login.ts:
```{javascript}
this.fb.login(permissions)
    .then(function(response){
      let userId = response.authResponse.userID;
      let params = new Array<string>();
```
response is of type FacebookLoginResponse, which in the source code of the facebook plugin has the following definition:
```{javascript}
export interface FacebookLoginResponse {
    status: string;
    authResponse: {
        session_key: boolean;
        accessToken: string;
        expiresIn: number;
        sig: string;
        secret: string;
        userID: string;
    };
}
```
so for your case, you want the accessToken, so to gather it :
```{javascript}
let accessToken = response.authResponse.accessToken;
```

**Comment by tiagomestreteixeira** [comment]
Or if you prefer to use arrow function (i do prefer):
```{javascript}
this.fb.login(permissions).then( (response: FacebookLoginResponse ) => {
      let accessToken = response.authResponse.accessToken;
}

**Comment by tomNjerry** [comment]
Thanks a lot  sir,
But I had one question can we get the user auth code instead access token ?

**Comment by tiagomestreteixeira** [comment]
@tomNjerry can you give a specific example? maybe i'm not understanding your question. The response that you receive from login method is a structure with the fields:
```
export interface FacebookLoginResponse {
    status: string;
    authResponse: {
        session_key: boolean;
        accessToken: string;
        expiresIn: number;
        sig: string;
        secret: string;
        userID: string;
    };
}
```
which is a standard oauth token.

For the system i'm building i uniquely identify a user in the system by its userID. It's a user identifier code for a given app. is it the field you're asking for? If it is the sample code in the line
```
let userId = response.authResponse.userID;
```
is already saving that userID into the variable userId.

**Comment by djabif** [comment]
Thanks @tiagomestreteixeira for your help!
