### ISSUE TITLE
side menu

### ISSUE THREAD

**Issue by manishsankari1** [ionicthemes/ionic2-facebook-login#4]
Hi Team,
Working on side menu, as user login in via facebook, in the side menu user detail like name and pic should be display. but ionViewCanEnter() seems not working here (app.component) please help.. my code...
`import { NativeStorage } from '';
import { Facebook } from '';

@component({
templateUrl: 'app.html'
})
export class MyApp {
@ViewChild(Nav) nav: Nav;

rootPage: any;

pages: Array<{title: string, component: any}>;
user: any;
userReady: boolean = false;
constructor(public fb: Facebook, public nativeStorage: NativeStorage, public platform: Platform, public statusBar: StatusBar, public splashScreen: SplashScreen) {

this.initializeApp();

// used for an example of ngFor and navigation
this.pages = [
  { title: 'Home', component: HomePage },
  { title: 'List', component: ListPage }
];

}

ionViewCanEnter(){
let env = this;
this.nativeStorage.getItem('user')
.then(function (data){
env.user = {
name: data.name,
gender: data.gender,
picture: data.picture
};
env.userReady = true;
}, function(error){
console.log(error);
});
}

initializeApp() {
this.platform.ready().then(() => {
// Okay, so the platform is ready and our plugins are available.
// Here you can do any higher level native things you might need.

  let env = this;
  this.nativeStorage.getItem('user')
  .then( function (data) {
    // user is previously logged and we have his data
    // we will let him access the app
    env.nav.push(HomePage);
    env.splashScreen.hide();
  }, function (error) {
    //we don't have the user data so we will ask him to log in
    env.nav.push(LoginPage);
    env.splashScreen.hide();

});

  this.statusBar.styleDefault();

});

}

openPage(page) {
// Reset the content nav to have just this page
// we wouldn't want the back button to show in this scenario
this.nav.setRoot(page.component);
}
}
`

**Comment by tiagomestreteixeira** [comment]
@manishsankari1, ionViewCanEnter is a page lifecycle. So because your MyApp is a component and not a page that lifecycle is not going to be called. Also that kind of logic goes into the lifecycle ionViewWillEnter or ionViewDidEnter, but not ionViewCanEnter. This last one is more appropriate for checking if a user is logged, for implementing a Guard. Check out http://ionicframework.com/docs/api/navigation/NavController/ for a list of the lifecycle page events. 
Cheers
