### ISSUE TITLE
Once logout, not possible to login again

### ISSUE THREAD

**Issue by sam-suresh** [ionicthemes/ionic2-facebook-login#5]
Hi

Once a user logout, not possible to login again. 
Tested on real device.

**Comment by djabif** [comment]
Hi, can you please debug you app to check if you are getting any error message?

**Comment by alvarheras** [comment]
Hi, good development. I have the same inssue . When y login second time i obtain that my key hash is invalid. What could be the problem? Thax . Only when login second time. First time its good

**Comment by djabif** [comment]
Updated to Ionic v4 and this is not happening anymore.
